### ISSUE TITLE
Issue generating run files

### ISSUE THREAD

**Issue by RaduNichita** [unikraft/app-elfloader#76]
When I run the commands from the README:

```bash
git clone https://github.com/unikraft/dynamic-apps
git clone https://github.com/unikraft/app-elfloader elfloader
cd elfloader/
./scripts/setup.sh
wget https://raw.githubusercontent.com/unikraft/app-testing/staging/scripts/generate.py -O scripts/generate.py
chmod a+x scripts/generate.py
./scripts/generate.py
[...]
```

I get the following error:

```console
./scripts/generate.py 
Traceback (most recent call last):
  File "/home/radu/work/master_new/elfloader/elfloader/./scripts/generate.py", line 506, in <module>
    sys.exit(main())
  File "/home/radu/work/master_new/elfloader/elfloader/./scripts/generate.py", line 502, in main
    generate_build()
  File "/home/radu/work/master_new/elfloader/elfloader/./scripts/generate.py", line 181, in generate_build
    with open(KRAFTCONFIG, "r", encoding="utf8") as stream:
FileNotFoundError: [Errno 2] No such file or directory: 'kraft.yaml'
```

**Comment by razvand** [comment]
This is going to be obsoleted by scripts in the [`catalog-for-maintainers` repository](https://github.com/unikraft/catalog-for-maintainers/).

Try replacing `kraft.yaml` with `Kraftfile` in the `generate.py` script.

**Comment by vliaskov** [comment]
> 
> Try replacing `kraft.yaml` with `Kraftfile` in the `generate.py` script.

Replacing `kraft.yaml` with `Kraftfile` results in:

```
~/app-elfloader> python3 scripts/generate.py 
Traceback (most recent call last):
  File "/home/user/app-elfloader/scripts/generate.py", line 506, in <module>
    sys.exit(main())
             ~~~~^^
  File "/home/user/app-elfloader/scripts/generate.py", line 502, in main
    generate_build()
    ~~~~~~~~~~~~~~^^
  File "/home/user/app-elfloader/scripts/generate.py", line 187, in generate_build
    if 'platform' not in target.keys():
                         ^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'keys'
```

How can Kraftifle (specifically targets) be parsed correctly by scripts/generate.py?

Or has the generate.py script been superseded by [`catalog-for-maintainers` repository](https://github.com/unikraft/catalog-for-maintainers/) , which was mentioned above?

Any other comments to solve the issue are welcome  (I can work on this with guidance)

Btw, https://github.com/unikraft/app-elfloader/issues/82 is a duplicate of this.
